### ISSUE TITLE
Output Question

### ISSUE THREAD

**Issue by Theo-Nelson** [Maggi-Chen/FusionSeeker#1]
Hello,

Recently, I've been working to integrate FusionSeeker into my long-read transcriptomics pipeline. I noticed that in the output, some of the spreadsheets do not have headers. Given that the pipeline is trying to serve non-experts, I thought it would be better to include some kind of descriptive header. 

I've been able from your comments and documentation to figure out most of the column meanings; however, Col H in the ```clustered_candidate.txt``` file eludes me. 

<img width="864" alt="Screen Shot 2022-08-26 at 1 04 46 PM" src="https://user-images.githubusercontent.com/99562847/186956409-9533ab39-5fe1-41bd-b79d-ca1cb49293e5.png">

Could you please let me know what that number represents?

Thank you very much!

Sincerely,
Theo

**Comment by Maggi-Chen** [comment]
Hello Theo,

Thank you for your interest in our tool! The file “confident_genefusion.txt” is the final output of gene fusion list, and “confident_genefusion_transcript_sequence.fa” includes the consensus transcript sequences for each fusion event.

The spreadsheet of “clustered_candidate.txt” is actually an intermediate file containing unfiltered fusion candidates, and it is usually a very long list. This file is kept just in case the results in “confident_genefusion.txt” are problematic, and I do not recommend you to use results in this file directly. In this file, Column A-B list the gene names/ids, C is number of reads supporting this event, D-G list locations of two breakpoints, H is the average mapping quality of supporting reads, and I is the read name of supporting reads. In Column H, sometimes there are two numbers (such as line 21 in the table you showed). hese two numbers represent mapping quality of two read alignments for the same read, and you can use either mean or max value of them (this usually occurs when only 1 read supports this event). 


Thanks,
Maggi

**Comment by Theo-Nelson** [comment]
Dear Maggi,

Thank you for the clarification. I'll frame the output per your suggestions!  

Sincerely,
Theo
